version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - 3002:5432
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
    volumes:
      - ./src/config/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql